### ISSUE TITLE
Decimal is not using precision

### ISSUE THREAD

**Issue by svallory** [tokilabs/lang#1]
Precision is fixed at 2 despite the constructor accepting a `precision` parameter.

https://github.com/cashfarm/node-lang/blob/master/src/decimal.ts

**Comment by albnunes** [comment]
Resolved in the last commit: https://github.com/tokilabs/lang/commit/d4f0883c2dbc5755d5875d935efa0c420d7a07e4

https://github.com/tokilabs/lang/blob/d4f0883c2dbc5755d5875d935efa0c420d7a07e4/src/decimal.ts#L9-L37

**Comment by albnunes** [comment]
The issue was resolved in the latest version of the package. I will close the issue.
