### ISSUE TITLE
Classify does not work

### ISSUE THREAD

**Issue by GabrielaRsanches** [tokilabs/lang#15]
The `options` object here should have `toClassOnly: true`

https://github.com/tokilabs/lang/blob/988b61b93583f9feb68d1b0f7d83f5a88cc806e7/src/serialization/decorators.ts#L42

**Comment by albnunes** [comment]
Resolved in the last commit: https://github.com/tokilabs/lang/commit/d4f0883c2dbc5755d5875d935efa0c420d7a07e4
