### ISSUE TITLE
Simplify Expose decorator

### ISSUE THREAD

**Issue by yfernandes** [tokilabs/lang#2]
Currently to expose a property under a different name we have to use

```
@Expose({ name: 'id' })
```

Can we make it so we can simply pass a string? e.g. `@Expose('id')`

**Comment by albnunes** [comment]
The exposed needs to receive which type of option, there are a few different options.
If you can think of a way to do this, please let me know. 

The code:
https://github.com/tokilabs/lang/blob/c350927ee3d2c42dce6f9a1c768618d6324936a7/src/serialization/decorators.ts#L67-L71

The interface:
https://github.com/tokilabs/lang/blob/c350927ee3d2c42dce6f9a1c768618d6324936a7/src/serialization/interfaces.ts#L78-L85

**Comment by yfernandes** [comment]
While I don't recall the use case I suggested this alternative method, I do remember the number of instances that were used with only the name property were much greater than the instances that had multiple properties set.
So the proposed implementation would be to accept as an options type an IExposeOptions object or a string.  If the object were passed the implementation would be the same, if a string was passed, however, we could assume that the string's value referred to the name property

**Comment by albnunes** [comment]
The issue was resolved in the latest version of the package. I will close the issue.
